config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  get "users/profile" => "users#show"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: 'static_pages#top'

  resources :shops do
    resources :parfaits, only: %i[new create edit update destroy show], shallow: true
  end

  resources :parfaits, only: %i[index]
  resources :reviews do
    collection do
      get :bookmarks
    end
  end
  resources :bookmarks, only: %i[create destroy]

  resource :privacy_policy, only: %i[show]
  resource :condition, only: %i[show]
end

app/models/shop.rb
class Shop < ApplicationRecord
  include JpPrefecture
  jp_prefecture :prefecture_code

  has_many :shop_opentimes, dependent: :destroy
  has_many :opentimes, through: :shop_opentimes
  has_many :shop_payments, dependent: :destroy
  has_many :payments, through: :shop_payments
  has_many :shop_features, dependent: :destroy
  has_many :features, through: :shop_features
  has_one :business, dependent: :destroy
  belongs_to :user

  has_many :parfaits, dependent: :destroy

  validates :name, presence: true, length: { maximum: 100 }, uniqueness: true
  validates :postal_code, presence: true, uniqueness: true, format: {with: /\A\d{7}\z/, message: "は7桁の半角数字で入力してください" }
  validates :prefecture_code, presence: true
  validates :city, presence: true
  validates :street, presence: true
  validates :tel, presence: true, uniqueness: true
  before_save :generate_address

  has_one_attached :shop_image

  validates :shop_image,
            content_type: %i(png jpg jpeg),                        # 画像の種類
            size: { less_than_or_equal_to: 5.megabytes },              # ファイルサイズ
            dimension: { width: { max: 2000 }, height: { max: 2000 } } # 画像の大きさ

  geocoded_by :full_address

  def image_as_thumbnail
    return unless shop_image.content_type.in?(%w[image/jpeg image/png])

    shop_image.variant(resize_to_limit: [400, 500])
  end

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end

  private

  def generate_address
    # buildingが空の場合は除外してaddressを生成
    self.full_address = [prefecture_name, city, street, other_address.presence].compact.join(" ")
  end

end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]

  def index
    @shops = Shop.order(created_at: :desc).page(params[:page]).per(10)

    shop_ids = @shops.pluck(:id)
    @shop_counts = Shop
                   .select("shops.id, COUNT(DISTINCT parfaits.id) AS parfaits_count, COUNT(reviews.id) AS reviews_count")
                   .left_joins(parfaits: :reviews)
                   .where(id: shop_ids)
                   .group("shops.id")
                   .index_by(&:id)
  end

  def new
    @form = ShopMustForm.new
  end

  def create
    # active_strageはshopとは別のデータベースに保存されるので、明示的に切り離しておく
    @form = ShopMustForm.new(shop_params)
    @form.user = current_user

    if @form.valid?
      @form.save
      redirect_to shop_path(@form.shop), success: '店舗登録が完了しました'
    else
      flash.now[:danger] = t('defaults.flash_message.not_created', item: Shop.model_name.human)
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    load_shop
    redirect_to root_path, alert: '他のユーザーが登録した店舗情報は編集できません' unless @shop.user == current_user

    @form = ShopMustForm.new(shop: @shop)
  end

  def update
    @shop = current_user.shops.find(params[:id])

    @form = ShopMustForm.new(shop_params, shop: @shop)

    if @form.valid?
      @form.save
      redirect_to @shop, success: '店舗情報が更新されました'
    else
      flash.now[:danger] = '店舗情報を更新できませんでした'
      render :edit, status: :unprocessable_entity
    end
  end

  def show
    load_shop
    @parfaits_count = @shop.parfaits.count
    @shop_parfait_reviews_count = @shop.parfaits.joins(:reviews).count
    @parfaits = @shop.parfaits
                     .left_joins(:reviews)
                     .select('parfaits.*, COUNT(reviews.id) AS reviews_count')
                     .group('parfaits.id')
                     .order(created_at: :desc)
    # 店舗毎のレビューを取得するので以下のようにします
    @reviews = Review.joins(:parfait)
                     .where(parfait: { shop_id: @shop.id })
                     .includes(:user)
                     .order(created_at: :desc)
    @bookmark_counts = Bookmark.where(review_id: @reviews.map(&:id)).group(:review_id).count
  end

  def destroy
    @shop = current_user.shops.find(params[:id])
    @shop.destroy!
    redirect_to shops_path, success: '削除に成功しました'
  end

  private

  def shop_params
    params.require(:shop).permit(:name, :postal_code, :prefecture_code, :city, :street, :other_address, :tel, :parking, :reservation,
                                 :shop_image, :remove_shop_image, :business_time, feature_ids: [], payment_ids: [])
  end

  def load_shop
    @shop = Shop.find(params[:id])
  end

end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_form.html.erb
<%= form_with model: form, data: { turbo: "false" }, class: "new_shop mt-4" do |f| %>
  <% if @form.errors.any? %>
    <div id="error_explanation" class="alert alert-danger mb-3">
      <ul class="mb-0">
        <% @form.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= f.label :name, class: "must-form" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <%= render "image_preview", f: f, form: form  %>

  <div class="mb-3">
    <%= f.label :postal_code, class: "must-form" %>
    <%= f.text_field :postal_code, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= f.label :prefecture_code, class: "must-form" %>
    <%= f.collection_select :prefecture_code, JpPrefecture::Prefecture.all, :code, :name, { prompt: '選択してください' }, class: 'form-select' %>
  </div>
  <div class="mb-3">
    <%= f.label :city, class: "must-form" %>
    <%= f.text_field :city, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= f.label :street, class: "must-form" %>
    <%= f.text_field :street, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= f.label :other_address %>
    <%= f.text_field :other_address, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= f.label :tel, class: "must-form" %>
    <%= f.telephone_field :tel, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= f.label :business_time, t("activerecord.attributes.business.business_time") %>
    <%= f.text_area :business_time, value: @form.business_time, placeholder: '例 月~金: 9:00~15:00, 17:00~21:00', class: "form-control", rows: "10" %>
  </div>
  <div class="mb-3">
    <%= f.label :reservation %>
    <%= f.check_box :reservation, class: "form-check-input" %>
  </div>
  <div class="mb-3">
    <%= f.label :parking %>
    <%= f.check_box :parking, class: "form-check-input" %>
  </div>
  <%= f.label :method_type, t("activerecord.attributes.payment.method_type") %>
  <%= f.collection_check_boxes :payment_ids, Payment.all, :id, :method_type do |b| %>
    <div>
      <%= b.label { b.check_box + b.text } %>
    </div>
  <% end %>
  </br>  
  <%= f.label :trait, t("activerecord.attributes.feature.trait") %>
  <%= f.collection_check_boxes :feature_ids, Feature.all, :id, :trait do |b| %>
    <div>
      <%= b.label { b.check_box + b.text } %>
    </div>
  <% end %>
  </br>
  <% if Rails.env.test? %>
    <%= f.submit '登録', class: "btn btn-primary" %>
  <% else %>  
    <%= f.button '登録', type: 'button', onclick: 'this.form.submit();', class: "btn btn-primary" %>
  <% end %>  
<% end %>

app/views/shops/_image_preview.erb
<div class="my-3" data-controller="previews" data-previews-width="400">
  <%= f.label :shop_image %><br>

  <%= f.file_field :shop_image,
    direct_upload: true,
    data: { previews_target: "input", action: "change->previews#previewImage" } %>

  <div data-previews-target="preview" class="mt-2">
    <% if f.object.shop_image.present? %>
      <%= image_tag f.object.shop_image %>
    <% end %>
  </div>

  <% if f.object.shop_image.present? %>
    <div>
      <%= f.check_box :remove_shop_image %>
      <%= f.label :remove_shop_image, "画像を削除する" %>
    </div>  
  <% end %>
</div>

app/views/shops/_image_preview.html.erb
<div class="my-3" data-controller="previews" data-previews-width="250">
  <%= f.label :店舗外観 %><br>

  <%= f.file_field :shop_image,
    direct_upload: true,
    data: { previews_target: "input", action: "change->previews#previewImage" } %>

  <div data-previews-target="preview">
    <% if f.object.shop_image.present? %>
      <%= image_tag f.object.shop_image, style: "max-width: 250px;" %>
    <% end %>
  </div>

  <% if f.object.shop_image.present? %>
    <div>
      <%= f.check_box :remove_shop_image %>
      <%= f.label :remove_shop_image, "画像を削除する" %>
    </div>  
  <% end %>
</div>

app/views/shops/_parfait_section_tab.erb
<% if user_signed_in? %>
  <%= link_to 'この店舗のパフェの登録ページはこちら', '#', class: 'btn-info', role: 'button' %>
<% end %>
<div class="container pt-3">
  <div class="row">
    <% if parfaits.present? %>
      <% parfaits.each do |parfait| %>
        <div class="d-flex flex-row align-items-center py-3 border-top border-bottom">
          <div class="d-flex">
            <%= image_tag 'noimage.png', class: "card-img-left" %>
            <div class="card-body">
              <h4 class="card-title">
                <%= link_to parfait.name, '#' %>
              </h4>
              <% if user_signed_in? %>
                <div class='d-flex justify-content-end'>
                  <%= link_to '#', id: "button-edit-#{parfait.id}" do %>
                    <i class='bi bi-pencil-fill'></i>
                  <% end %>
                  <%= link_to shop_path(shop), id: "button-delete-#{parfait.id}", data: { turbo_method: :delete, turbo_confirm: t('defaults.delete_confirm') } do %>
                    <i class="bi bi-trash-fill"></i>
                  <% end %>
                </div>
              <% end %>  
              <p class="card-text">
                紹介文
              </p> 
              <p>価格帯</p>
              <p>星評価</p>
              <p>レビュー： 件</p>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <div class="mb-3">パフェの情報がありません</div>
    <% end %>
  </div>
</div>   



          

app/views/shops/_parfait_section_tab.html.erb
<div class="container pt-3">
  <% if user_signed_in? %>
    <div class="text-end mb-5">
      <%= link_to 'この店舗のパフェの登録ページはこちら', new_shop_parfait_path(shop), class: "btn btn-outline-primary", role: 'button' %>
    </div>
  <% end %>

  <% if parfaits.present? %>
    <% parfaits.each do |parfait| %>
      <div class="d-flex style="min-height: 150px;">

        <!-- 画像エリア -->
        <div style="flex: 0 0 25%;">
          <div class="index-photo">
            <%= image_tag parfait.parfait_image.present? ? parfait.parfait_image : 'noimage.png' %>
          </div>  
        </div>

        <div style="flex: 1; padding-left: 1rem;">
          <div class="d-flex">
            <h4>
              <%= link_to parfait.name, parfait_path(parfait) %>
            </h4>
            <% if user_signed_in? %>
              <% if current_user.own?(parfait) %>
                <div class='ms-auto d-flex'>
                  <div class="d-flex">
                    <%= link_to edit_parfait_path(parfait), id: "button-edit-#{parfait.id}", class: "me-2" do %>
                      <i class='bi bi-pencil-fill'></i> 編集
                    <% end %>
                    <%= link_to parfait_path(parfait), id: "button-delete-#{parfait.id}", data: { turbo_method: :delete, turbo_confirm: t('defaults.delete_confirm') } do %>
                      <i class="bi bi-trash-fill"></i> 削除
                    <% end %>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>  
          <div>
            <%= link_to parfait.shop.name, shop_path(parfait.shop) %>
          </div>

          <div class="custom-line"></div>

          <div>価格帯：<%= parfait.price_i18n %></div>
          <% if parfait.is_limited? %> 
            <div>期間限定商品</div>
          <% else %>
            <div>レギュラー商品</div>
          <% end %> 
          <div>評価：</div>
          <div title="評価機能は後で実装予定です！お楽しみに！", class="star-size">☆☆☆☆☆</div>
          <div>レビュー： <%= parfait.reviews_count %>件</div>
        </div>
      </div>
      <div class="custom-line"></div>
    <% end %>
  <% else %>
    <div class="mb-3 no-date">パフェの情報がありません</div>
  <% end %>
</div>   



        

app/views/shops/_reviews_section_tab.html.erb
<div class="container pt-5">
  <% if reviews.present? %>
    <% reviews.each do |review| %>
      <% bookmark_count = bookmark_counts[review.id] || 0 %>
      <div class="d-flex style="min-height: 150px;">

        <div style="flex: 0 0 25%;">
          <div class="index-photo">
            <%= image_tag review.review_images.present? ? review.review_images.last : 'noimage.png' %>
          </div>  
        </div>

        <div style="flex: 1; padding-left: 1rem;">
          <div class="d-flex">
            <h4>
              <%= link_to review.title, review_path(review) %>
            </h4>
            <div class='ms-auto d-flex'>
              <% if user_signed_in? %>
                <% if current_user&.own?(review) %>
                  <div class='d-flex'>
                    <%= link_to edit_review_path(review), id: "button-edit-#{review.id}", class: "me-2" do %>
                      <i class='bi bi-pencil-fill'></i> 編集
                    <% end %>
                    <%= link_to review_path(review), id: "button-delete-#{review.id}", data: { turbo_method: :delete, turbo_confirm: t('defaults.delete_confirm') } do %>
                      <i class="bi bi-trash-fill"></i> 削除
                    <% end %>
                  </div>
                <% else %>
                  <div>
                    <%= render 'shared/bookmark_buttons', review: review, bookmark: current_user.bookmarks.find_by(review_id: review.id), bookmark_count: bookmark_count %>
                  </div>    
                <% end %>
              <% end %>
            </div>  
          </div>  
          <ul class="list-inline">
            <li><i class="bi bi-person"></i><%= review.user.name %></li>
            <li><i class="bi bi-calendar"></i><%= l review.created_at, format: :short %></li>
          </ul>

          <div class="custom-line"></div>
          <div><%= link_to review.parfait.name, parfait_path(review.parfait) %></div>
          <div title="評価機能は後で実装予定です！お楽しみに！">☆☆☆☆☆</div>
          <div class="custom-line"></div>
          <div class="review-body-preview">
            <%= simple_format(review.body) %>
          </div>  
        </div>
      </div>
      <div class="custom-line"></div>
    <% end %>
  <% else %>
    <div class="mb-3 no-date">レビューがありません</div>
  <% end %>
</div>

app/views/shops/_shop.html.erb
<% if shop.shop_image.attached? && shop.shop_image.content_type.in?(%w[image/jpeg image/png]) %>
  <div><%= image_tag(shop.image_as_thumbnail, height: "500", class: "img-fluid") %></div>
<% end %>

app/views/shops/_show_header.erb
<div>
  <h3><%= shop.name %></h3>
  <div>住所：<%= shop.full_address %></div>
  <div>電話番号：<%= shop.tel %><div>
</div>

app/views/shops/_top_section_tab.erb
<div class="container pt-5">
  <div class="row mb-3">
    <div class="col-lg-8 offset-lg-2">
      <h1>店舗詳細</h1>
      <article class="d-flex flex-row align-items-center py-3 border-top border-bottom">
        <div class="card-body">
          <div class="row">
            <div class="col-md-3">
              <%= image_tag 'noimage.png', width: "300", height: "200", class: "card-img-top img-fluid" %>
            </div>
            <div class="col-md-9">
              <h3><%= shop.name %></h3>
              <div>住所：<%= shop.full_address %></div>
              <div>電話番号：<%= shop.tel %><div>
              <% if user_signed_in? %>
                <div class='d-flex justify-content-end'>
                  <%= link_to edit_shop_path(shop), id: "button-edit-#shop.id}" do %>
                    <i class='bi bi-pencil-fill'></i>
                  <% end %>
                  <%= link_to shop_path(shop), id: "button-delete-#{shop.id}", class: "ms-2", data: { turbo_method: :delete, turbo_confirm: t('defaults.delete_confirm') } do %>
                    <i class="bi bi-trash-fill"></i>
                  <% end %>
                </div>
              <% end %> 
            </div>
          </div>
        </div>  
      </article>
      <div class="d-flex flex-row align-items-center py-3 border-top border-bottom">
      このあたりに画像起きたい
      </div>
      <div class="d-flex flex-row align-items-center py-3 border-top border-bottom mb-5">
        <h5 class="mb-0 me-5">営業時間</h5>
        <% if shop.business.present? && shop.business.business_time.present? %>
          <p class="mb-0">
            <%= simple_format(shop.business.business_time) %>
          </p>
        <% else %>
          <p class="mb-0">営業時間の情報はありません<p>
        <% end %>  
      </div>
      <h4>店舗基本情報</h4>
      <table class="s-table table_under">
        <tbody>
          <tr>
            <th>店名</th>
            <td>
              <div>
                <%= shop.name %>
              </div>
            </td>
          </tr>
          <tr>
            <th>住所</th>
            <td>
              <div>
                <%= shop.full_address %>
              </div>
            </td>   
          </tr>
          <tr>
            <th>電話番号</th>
            <td>
              <div>
                <%= shop.tel %>
              </div>
            </td>
          </tr>
          <tr>
            <th>営業時間</th>
            <td>
              <% if shop.business.present? && shop.business.business_time.present? %> 
                <div>
                  <%= simple_format(shop.business.business_time) %>
                </div>
              <% else %>
                <div>営業時間の情報はありません</div>
              <% end %>    
            </td>
          </tr>
          <tr>
            <th>予約</th>
            <td>
              <% if shop.reservation? %> 
                <div>予約可</div>
              <% else %>
                <div>予約不可</div>
              <% end %>    
            </td>
          </tr>
          <tr>
            <th>駐車場</th>
            <td>
              <% if shop.parking? %> 
                <div>駐車場有</div>
              <% else %>
                <div>駐車場無</div>
              <% end %>    
            </td>
          </tr>
          <tr>
            <th>支払い方法</th>
            <td>
              <% if shop.payment_ids.present? %> 
                <div>
                  <%= shop.payments.pluck(:method_type).join(', ') %>
                </div>
              <% end %>    
            </td>
          </tr>
          <tr>
            <th>店の特徴</th>
            <td>
              <% if shop.feature_ids.present? %> 
                <div>
                  <%= shop.features.pluck(:trait).join(', ') %>
                </div>
              <% end %>    
            </td>
          </tr>


        </tbody>

      
      </table>
    </div>
  </div>
</div>

app/views/shops/_top_section_tab.html.erb
<div class="pt-5">
  <h2>店舗詳細</h2>
  <div class="top-top border-top border-bottom m-3">
    <div class="py-4">
      <div class="row">
        <div class="col-7">
          <% if shop.shop_image.attached? %>
            <div class="show-image">
              <%= image_tag(shop.image_as_thumbnail) %>
            </div>
          <% else %>
            <div class="show-image">
              <%= image_tag 'noimage.png' %>
            </div>
          <% end %>
        </div>
        <div class="col-5">
          <h4 class="card-title mb-1">
            <%= shop.name %>
          </h4>
          <div>
            <%= "住所: #{shop.full_address}" %>
          </div>

          <% if user_signed_in? %>
            <% if current_user.own?(shop) %>
              <div class='text-end'>
                <!-- rspecテストのためにid必要です -->
                <%= link_to edit_shop_path(shop), id: "button-edit-#{shop.id}", class: "me-2" do %>
                  <i class='bi bi-pencil-fill'></i> 編集
                <% end %>
                <%= link_to shop_path(shop), id: "button-delete-#{shop.id}", data: { turbo_method: :delete, turbo_confirm: t('defaults.delete_confirm') } do %>
                  <i class="bi bi-trash-fill"></i> 削除
                <% end %>
              </div>
            <% end %>
          <% end %>

          <div class="custom-line"></div>
          <div title="評価機能は後で実装予定です！お楽しみに！", class="star-size mb-3">☆☆☆☆☆</div>
          <div class="mb-1">
            登録パフェ： <%= parfaits_count %>件
          </div>
          <div>
            レビュー数： <%= shop_parfait_reviews_count %>件
          </div>  
        </div>  
      </div>
    </div>  
  </div>
  <div class="pt-5">
    <table class="s-table table_under">
      <h4>店舗情報（詳細）</h4>
      <tbody>
        <tr>
          <th>店名</th>
          <td>
            <div>
              <%= shop.name %>
            </div>
          </td>
        </tr>
        <tr>
          <th>住所</th>
          <td>
            <div>
              <%= shop.full_address %>
            </div>
            <div id="map" style="height: 400px;", class="mt-3"></div>
          </td>   
        </tr>
        <tr>
          <th>電話番号</th>
          <td>
            <div>
              <%= shop.tel %>
            </div>
          </td>
        </tr>
        <tr>
          <th>営業時間</th>
          <td>
            <% if shop.business.present? && shop.business.business_time.present? %> 
              <div>
                <%= simple_format(shop.business.business_time) %>
              </div>
            <% else %>
              <div>営業時間の情報はありません</div>
            <% end %>    
          </td>
        </tr>
        <tr>
          <th>予約</th>
          <td>
            <% if shop.reservation? %> 
              <div>予約可</div>
            <% else %>
              <div>予約不可</div>
            <% end %>    
          </td>
        </tr>
        <tr>
          <th>駐車場</th>
          <td>
            <% if shop.parking? %> 
              <div>駐車場有</div>
            <% else %>
              <div>駐車場無</div>
            <% end %>    
          </td>
        </tr>
        <tr>
          <th>支払い方法</th>
          <td>
            <% if shop.payment_ids.present? %> 
              <div>
                <%= shop.payments.pluck(:method_type).join(', ') %>
              </div>
            <% end %>    
          </td>
        </tr>
        <tr>
          <th>店の特徴</th>
          <td>
            <% if shop.feature_ids.present? %> 
              <div>
                <%= shop.features.pluck(:trait).join(', ') %>
              </div>
            <% end %>    
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

<br>

<script>
  function initMap(){
    // 地図の経度・緯度を取得
    let mapPosition = {lat: <%= shop.latitude || 0 %> , lng: <%= shop.longitude || 0 %> };
    let map = new google.maps.Map(document.getElementById('map'), {
      zoom: 15,
      center: mapPosition
    });
    let transitLayer = new google.maps.TransitLayer();
    transitLayer.setMap(map);
    
    let contentString = '【住所】<%= shop.full_address %>';
    let infowindow = new google.maps.InfoWindow({
      content: contentString
    });

    let marker = new google.maps.Marker({
      position: mapPosition,
      map: map,
      title: contentString
    });

    marker.addListener('click', function(){
      infowindow.open(map, marker);
    });
  }
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=<%= Rails.application.credentials.dig(:google, :google_map_api_key) || ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap" async defer></script>

app/views/shops/edit.html.erb
<div class="form-wrapper">
  <div class="container shop-page">
    <div class="container">
      <h2>店舗編集</h2>
      <%= render 'form', form: @form %>
    </div>
  </div>
</div>

app/views/shops/index.html.erb
<% breadcrumb :shop_index %>
<div class="index-wrapper">
  <div class="container pt-3 index-page">
    <% if user_signed_in? %>
      <div class="text-end mb-3">
        <%= link_to '店舗登録ページはこちら', new_shop_path, class: "btn btn-outline-primary", role: 'button' %>
      </div>  
    <% end %>

    <h2 class="mb-5">店舗一覧</h2>

    <% if @shops.present? %>
      <% @shops.each do |shop| %>
        <div class="d-flex style="min-height: 150px;">
          
          <!-- 画像 -->
          <div style="flex: 0 0 25%;">
            <div class="index-photo">
              <%= image_tag shop.shop_image.present? ? shop.shop_image : 'noimage.png' %>
            </div>  
          </div>

          <!-- 文字 -->
          <div style="flex: 1; padding-left: 1rem;">
            <div class="d-flex">
              <h4>
                <%= link_to shop.name, shop_path(shop) %>
              </h4>

              <% if user_signed_in? %>
                <% if current_user.own?(shop) %>
                  <div class="ms-auto d-flex">
                    <div class='d-flex'>
                      <%= link_to edit_shop_path(shop), id: "button-edit-#{shop.id}", class: "me-2" do %>
                        <i class='bi bi-pencil-fill'></i> 編集
                      <% end %>
                      <%= link_to shop_path(shop), id: "button-delete-#{shop.id}", data: { turbo_method: :delete, turbo_confirm: t('defaults.delete_confirm') } do %>
                        <i class="bi bi-trash-fill"></i> 削除
                      <% end %>
                    </div>
                  </div>
                <% end %>  
              <% end %>
            </div>

            <div>
              <%= "住所: #{shop.full_address}" %>
            </div>

            <div class="custom-line"></div>

            <% counts = @shop_counts[shop.id] %>
            <div>評価：</div>
            <div title="評価機能は後で実装予定です！お楽しみに！", class="star-size">☆☆☆☆☆</div>
            <div>登録パフェ： <%= counts&.parfaits_count || 0 %>件</div>
            <div>全レビュー数： <%= counts&.reviews_count || 0 %>件</div>
          </div>
        </div>  
        <div class="custom-line"></div>
      <% end %>
    <% else %>
      <div class="mb-3 no-date">店舗情報がありません</div>
    <% end %>
    <div class="p-2">
      <%= paginate @shops, theme: 'bootstrap-5' %>
    </div>  
  </div>
</div>

app/views/shops/new.html.erb
<div class="form-wrapper">
  <div class="container shop-page">
    <div class="container">
      <h2>店舗登録</h2>
      <%= render 'form', form: @form %>
    </div>
  </div>
</div>

app/views/shops/show.html.erb
<% breadcrumb :shop_show, @shop %>
<div class="show-wrapper">
  <div class="container show-page pt-3">
    <%= render 'shops/show_header', shop: @shop %>
    <div class="tabs">
      <ul class="nav nav-tabs">
        <li class="nav-item">
          <button class="nav-link active" data-bs-toggle="tab" data-bs-target="#section1" type="button">トップ</button>
        </li>
        <li class="nav-item">
          <button class="nav-link" data-bs-toggle="tab" data-bs-target="#section2" type="button">パフェ一覧</button>
        </li>
        <li class="nav-item">
          <button class="nav-link" data-bs-toggle="tab" data-bs-target="#section3" type="button">レビュー</button>
        </li>
      </ul>
      
      <div class="tab-content">
        <div id="section1" class="tab-pane fade show active">
          <%= render 'shops/top_section_tab', shop: @shop, parfaits_count: @parfaits_count, shop_parfait_reviews_count: @shop_parfait_reviews_count %>
        </div>
        <div id="section2" class="tab-pane fade">
          <%= render 'shops/parfait_section_tab', parfaits: @parfaits, shop: @shop %>
        </div>
        <div id="section3" class="tab-pane fade">
          <%= render 'shops/reviews_section_tab', reviews: @reviews, bookmark_counts: @bookmark_counts %>
        </div>
      </div>
    </div>
  </div>
</div>