config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  get "users/profile" => "users#show"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: 'static_pages#top'

  resources :shops do
    resources :parfaits, only: %i[new create edit update destroy show], shallow: true
  end

  resources :parfaits, only: %i[index]
  resources :reviews do
    collection do
      get :bookmarks
    end
  end
  resources :bookmarks, only: %i[create destroy]

  resource :privacy_policy, only: %i[show]
  resource :condition, only: %i[show]
end

app/views/shared/_bookmark.html.erb
<%= link_to bookmarks_path(review_id: review.id), id: "bookmark-button-for-review-#{review.id}", data: { turbo_method: :post } do %>
  <i class="bi bi-heart"></i>
<% end %>

app/views/shared/_bookmark_buttons.html.erb
<div class="d-inline-flex align-items-center">
  <% if current_user.bookmark?(review) %>
    <%= render 'shared/unbookmark', { review: review } %>
  <% else %>
    <%= render 'shared/bookmark', { review: review } %>
  <% end %>

  <% if bookmark_count.to_i > 0 %>
    <div class="m-1 text-muted">
      <%= bookmark_count %>
    </div>
  <% end %>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <% bootstrap_class = case message_type.to_sym
    when :notice then "success"
    when :alert  then "danger"
    when :success, :danger, :warning, :info then message_type
    else "secondary"
  end %>
  <div class="alert alert-<%= bootstrap_class %> alert-dismissible fade show">
    <%= message %>
    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
  </div>
<% end %>

<%#
  この条件分岐はdeviseにフラッシュメッセージを適応させるため。
  flashの中でmessage_typeが文字列のときもあるので
  message_type.to_symでシンボルにする。
  後はnoticeとかをbootstrapに合わせたクラス名に変換する。
%>

app/views/shared/_footer.html.erb
<footer id='footer' class='footer pt-3'>
  <div class='container'>
    <div class='row'>
      <div class='col-sm-6 col-12'>
        <ul class="list-inline text-center text-sm-start mb-3">
          <li class='list-inline-item'>
            <%= link_to 'プライバシーポリシー', privacy_policy_path, class: 'text-decoration-none text-muted' %>
          </li>
          <li class='list-inline-item'>
            <%= link_to '利用規約', condition_path, class: 'text-decoration-none text-muted' %>
          </li>  
        </ul>
        <div class='copyright text-center text-sm-start'>
          <p>© 2025 erika. All rights reserved</p>
        </div>
      </div>

      <div class='col-sm-6 col-12 text-center text-sm-end d-flex flex-column justify-content-center'>
        <div class='text-warning fs-4'>parfaitcollection1111@gmail.com</div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="header">
  <div class="container-fluid">
    <%= link_to '/', class: 'navbar-brand ms-4' do %>
      <%= image_tag 'pafecolle_logo.png', alt: "パフェコレ", height: "80" %>
    <% end %>
  </div>

  <% if current_page?(root_path) %>
    <div class="container-fluid d-flex justify-content-between px-4 header-illust">
      <%= image_tag 'chestnut_illust.jpg', class: 'header-image' %>
      <%= image_tag 'icecream_illust.jpg', class: 'header-image' %>
      <%= image_tag 'parfait_illust.jpg', class: 'header-image' %>
      <%= image_tag 'peach_illust.jpg', class: 'header-image' %>
      <%= image_tag 'blueberry_illust.jpg', class: 'header-image' %>
    </div>
  <% end %>

  <div class="container-fluid d-flex justify-content-end mt-auto">
    <nav class='navbar navbar-expand-lg'>
      <button class='navbar-toggler' data-bs-toggle='collapse' data-bs-target='#navbarSupportedContent'
        aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
        <span class='navbar-toggler-icon'></span>
      </button>
      <div class='collapse navbar-collapse p-3' id='navbarSupportedContent'>
        <ul class='navbar-nav ms-auto main-nav align-items-center'>
          <li class='nav-item'>
            <%= link_to '口コミから探す', reviews_path, class: 'nav-link' %>
          </li>

          <li class='nav-item'>
            <%= link_to '店舗から探す', shops_path, class: 'nav-link' %>
          </li>

          <li class='nav-item'>
            <%= link_to '商品から探す', parfaits_path, class: 'nav-link' %>
          </li>

          <li class='nav-item'>
            <%= link_to 'ランキング', '#', class: 'nav-link' %>
          </li>

          <% if user_signed_in? %>
            <li class='nav-item dropdown dropdown-slide'>
              <%= link_to '#', class: 'nav-link', data: { bs_toggle: 'dropdown' }, aria: { haspopup: 'true', expanded: 'false' }, id: 'header-profile' do %>
                <% if current_user.avatar.present? %>
                  <%= image_tag current_user.avatar, class: 'rounded-circle mr15', width: '40', height: '40' %>
                <% else %>  
                  <%= image_tag 'noimage.png', class: 'rounded-circle mr15', width: '40', height: '40' %>
                <% end %>
              <% end %>
              <div class='dropdown-menu dropdown-menu-end'>
                <div class='dropdown-item'><%= current_user.name %></div>
                <div class='dropdown-divider'></div>
                <%= link_to 'プロフィール', users_profile_path, class: 'dropdown-item' %>
                <%= link_to t('header.bookmark_index'), bookmarks_reviews_path, class: 'dropdown-item' %>
                <%= link_to 'ログアウト', destroy_user_session_path, class: 'dropdown-item', data: { turbo_method: :delete } %>
              </div>
            </li>
          <% else %>
            <li class='nav-item'>
              <%= link_to 'ログイン', new_user_session_path, class: 'nav-link' %>
            </li>

            <li class='nav-item'>
              <%= link_to 'ユーザ登録', new_user_registration_path, class: 'nav-link' %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
  </div>  
</header>

app/views/shared/_unbookmark.html.erb
<%= link_to bookmark_path(current_user.bookmarks.find_by(review_id: review.id)), id: "unbookmark-button-for-review-#{review.id}", data: { turbo_method: :delete } do %>
  <i class="bi bi-heart-fill"></i>
<% end %>