config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  get "users/profile" => "users#show"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: 'static_pages#top'

  resources :shops do
    resources :parfaits, only: %i[new create edit update destroy show], shallow: true
  end

  resources :parfaits, only: %i[index]
  resources :reviews do
    collection do
      get :bookmarks
    end
  end
  resources :bookmarks, only: %i[create destroy]

  resource :privacy_policy, only: %i[show]
  resource :condition, only: %i[show]
end

app/models/parfait.rb
class Parfait < ApplicationRecord
  belongs_to :shop
  belongs_to :user

  validates :name, presence: true, length: { maximum: 100 }
  validates :body, length: { maximum: 500 }
  validates :price, presence: true
  has_many :reviews, dependent: :destroy

  has_one_attached :parfait_image

  validates :parfait_image,
            content_type: %i(png jpg jpeg),                        # 画像の種類
            size: { less_than_or_equal_to: 10.megabytes },              # ファイルサイズ
            dimension: { width: { max: 2000 }, height: { max: 2000 } } # 画像の大きさ

  def image_as_thumbnail
    return unless parfait_image.content_type.in?(%w[image/jpeg image/png])

    parfait_image.variant(resize_to_limit: [400, 500]).processed
  end

  attr_accessor :remove_parfait_image

  enum price: {
    under_1000: 0,
    under_1500: 1,
    under_2000: 2,
    under_3000: 3,
    under_4000: 4,
    under_5000: 5,
    under_6000: 6,
    under_7000: 7,
    under_8000: 8,
    under_9000: 9,
    under_10000: 10,
    over_10000: 11
  }

end

app/controllers/parfaits_controller.rb
class ParfaitsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  def index
    @parfaits = Parfait.includes(:shop).order(created_at: :desc).page(params[:page]).per(10)

    parfait_ids = @parfaits.pluck(:id)
    @parfait_counts = Parfait
                      .select("parfaits.id, COUNT(reviews.id) AS reviews_count")
                      .left_joins(:reviews)
                      .where(id: parfait_ids)
                      .group("parfaits.id")
                      .index_by(&:id)
  end

  def show
    load_parfait
    @reviews = @parfait.reviews.order(created_at: :desc)
    @bookmark_counts = Bookmark.where(review_id: @reviews.map(&:id)).group(:review_id).count
  end

  def new
    @parfait = Parfait.new
  end

  def create
    @parfait = current_user.parfaits.new(parfait_params)

    # まずレコードを保存してから画像を添付する
    if @parfait.save
      if params[:parfait][:parfait_image].present?
        @parfait.parfait_image.attach(params[:parfait][:parfait_image])
        @parfait.save # 再度保存することで画像をデータベースに関連付け
      end
      redirect_to @parfait, success: 'パフェ情報が登録されました'
    else
      Rails.logger.debug "Parfait errors: #{@parfait.errors.full_messages}"
      flash.now[:danger] = t('defaults.flash_message.not_created', item: Parfait.model_name.human)
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @parfait = current_user.parfaits.find(params[:id])
    if @parfait.nil?
      redirect_to root_path, alert: '他のユーザーが登録したパフェ情報は編集できません'
    end
  end

  def update
    @parfait = current_user.parfaits.find(params[:id])

    # まず、普通のテキスト情報だけ更新する
    if @parfait.update(parfait_params)

      # もし画像を消したいって指示があったら、ここで削除する
      if params[:parfait][:remove_parfait_image] == '1'
        @parfait.parfait_image.purge if @parfait.parfait_image.attached?
      end

      # 新しい画像がアップロードされてたら、ここでつけ直す
      if params[:parfait][:parfait_image].present?
        # いったん古い画像があれば消してから
        @parfait.parfait_image.purge if @parfait.parfait_image.attached?
        # 新しい画像を保存
        @parfait.parfait_image.attach(params[:parfait][:parfait_image])
      end

      redirect_to @parfait, success: 'パフェ情報が更新されました', status: :see_other
    else
      flash.now[:danger] = "パフェ情報を更新できませんでした"
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @parfait = current_user.parfaits.find(params[:id])
    @parfait.destroy!
    redirect_to parfaits_path, success: '削除に成功しました'
  end

  private

  def parfait_params
    params.require(:parfait).permit(:name, :body, :price, :is_limited).merge(shop_id: params[:shop_id] || @parfait&.shop_id)
  end

  def load_parfait
    @parfait = Parfait.includes(:shop).find(params[:id])
  end

end

app/helpers/parfaits_helper.rb
module ParfaitsHelper
end

app/views/parfaits/_form.html.erb
<%= form_with model: parfait, url: parfait.persisted? ? parfait_path(parfait) : shop_parfaits_path, local: true, class: "new_parfait mt-4", data: { turbo: "false" } do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="mb-3">
    <%= f.label :name, class: "must-form" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <%= render "image_parfait_preview", f: f, parfait: parfait %>

  <%# enumのキーを送っても自動的に値に変換されるのでkだけで大丈夫 %>
  <div class="mb-3">
    <%= f.label :price, '価格', class: "must-form" %>
    <%= f.select :price, Parfait.prices.keys.map {|k| [I18n.t("enums.parfait.price.#{k}"), k]}, { prompt: '価格を選択してください' }, class: 'form-select' %>
  </div>
  <div class="mb-3">
    <%= f.label :is_limited, '期間限定商品でしょうか？' %>
    <%= f.check_box :is_limited, class: "form-check-input" %>
  </div>
  <div class="mb-3">
    <%= f.label :body, '商品紹介' %>
    <%= f.text_area :body, class: "form-control", rows: "5", placeholder: '簡単な特徴の記入をお願いします' %>
  </div>

  <%# デフォルトのenterで送信する機能で送信されないためのダミー %>
  <%= tag.input type: 'submit', style: 'display:none', disabled: true %>

  <%= f.submit '登録', class: "btn btn-primary" %>
<% end %>

app/views/parfaits/_image_parfait_preview.erb
<div class="my-3" data-controller="previews" data-previews-width="400">
  <%= f.label :パフェの画像 %><br>

  <%= f.file_field :parfait_image,
    direct_upload: true,
    data: { previews_target: "input", action: "change->previews#previewImage" } %>

  <div data-previews-target="preview" class="mt-2">
    <% if f.object.parfait_image.present? %>
      <%= image_tag f.object.parfait_image %>
    <% end %>
  </div>

  <% if f.object.parfait_image.present? %>
    <div>
      <%= f.check_box :remove_parfait_image %>
      <%= f.label :remove_parfait_image, "画像を削除する" %>
    </div>  
  <% end %>
</div>

app/views/parfaits/_reviews_section_tab.html.erb
<div class="container pt-3">
  <% if user_signed_in? %>
    <div class="text-end mb-5">
      <%= link_to 'このパフェのレビュー投稿はこちら', new_review_path(parfait_id: parfait.id), class: 'btn btn-outline-primary', role: 'button' %>
    </div>  
  <% end %>

  <% if reviews.present? %>
    <% reviews.each do |review| %>
      <% bookmark_count = bookmark_counts[review.id] || 0 %>
      <div class="d-flex style="min-height: 150px;">

        <div style="flex: 0 0 25%;">
          <div class="index-photo">
            <%= image_tag review.review_images.present? ? review.review_images.last : 'noimage.png' %>
          </div>
        </div>

        <div style="flex: 1; padding-left: 1rem;">
          <div class="d-flex">
            <h4>
              <%= link_to review.title, review_path(review) %>
            </h4>
            <div class='ms-auto d-flex'>
              <% if user_signed_in? %>
                <% if current_user&.own?(review) %>
                  <div class='d-flex'>
                    <%= link_to edit_review_path(review), id: "button-edit-#{review.id}", class: "me-2" do %>
                      <i class='bi bi-pencil-fill'></i> 編集
                    <% end %>
                    <%= link_to review_path(review), id: "button-delete-#{review.id}", data: { turbo_method: :delete, turbo_confirm: t('defaults.delete_confirm') } do %>
                      <i class="bi bi-trash-fill"></i> 削除
                    <% end %>
                  </div>
                <% else %>
                  <div>
                    <%= render 'shared/bookmark_buttons', review: review, bookmark: current_user.bookmarks.find_by(review_id: review.id), bookmark_count: bookmark_count %>
                  </div>    
                <% end %>
              <% end %>
            </div>
          </div>
          <ul class="list-inline">
            <li><i class="bi bi-person"></i><%= review.user.name %></li>
            <li><i class="bi bi-calendar"></i><%= l review.created_at, format: :short %></li>
          </ul>
          <div class="custom-line"></div>
          <div><%= link_to review.parfait.name, parfait_path(review.parfait) %></div>
          <div title="評価機能は後で実装予定です！お楽しみに！">☆☆☆☆☆</div>
          <div class="custom-line"></div>
          <div class="review-body-preview">
            <%= simple_format(review.body) %>
          </div>
        </div>
      </div>
      <div class="custom-line"></div>
    <% end %>
  <% else %>
    <div class="mb-3 no-date">レビューがありません</div>
  <% end %>
</div>

app/views/parfaits/_top_section_tab.html.erb
<div class="pt-5">
  <h2>パフェ詳細</h2>
  <div class="top-top border-top border-bottom m-3">
    <div class="py-4">
      <div class="row">
        <div class="col-7">
          <% if parfait.parfait_image.attached? %>
            <div class="show-image">
              <%= image_tag(parfait.image_as_thumbnail) %>
            </div>
          <% else %>    
            <div class="show-image">
              <%= image_tag 'noimage.png' %>
            </div>
          <% end %>
        </div>
        <div class="col-5">
          <h3><%= parfait.name %></h3>
          <h5>店舗：<%= link_to parfait.shop.name, shop_path(parfait.shop) %></h5>
          <% if user_signed_in? %>
            <% if current_user.own?(parfait) %>
              <div class='text-end'>
                <%= link_to edit_parfait_path(parfait), id: "button-edit-#{parfait.id}", class: "me-2" do %>
                  <i class='bi bi-pencil-fill'></i> 編集
                <% end %>
                <%= link_to parfait_path(parfait), id: "button-delete-#{parfait.id}", class: "ms-2", data: { turbo_method: :delete, turbo_confirm: t('defaults.delete_confirm') } do %>
                  <i class="bi bi-trash-fill"></i> 削除
                <% end %>
              </div>
            <% end %>
          <% end %>

          <div class="custom-line"></div>
          <% if parfait.is_limited? %> 
            <div>期間限定商品</div>
          <% else %>
            <div>レギュラー商品</div>
          <% end %>
          <div>価格帯：<%= parfait.price_i18n %></div>
          <p><%= simple_format(parfait.body) %></p>
        </div>
      </div>
    </div>  
  </div> 
</div>

app/views/parfaits/edit.html.erb
<div class="form-wrapper">
  <div class="container parfait-page">
    <div class="container">
      <h2>商品編集</h2>
      <div class="pt-2">
        <h4><%= @parfait.shop.name %></h4>
      </div>
      <%= render 'form', parfait: @parfait %>
    </div>
  </div>
</div>

app/views/parfaits/index.html.erb
<div>
  <% breadcrumb :parfait_index %>
</div>
<div class="pt-3 pe-5 text-end">☆パフェの登録は店舗詳細ページからできます！☆</div>
<div class="index-wrapper">
  <div class="container pt-3 index-page">
    <h2 class="mb-5">パフェ一覧</h2>
    <% if @parfaits.present? %>
      <% @parfaits.each do |parfait| %>
        <div class="d-flex style="min-height: 150px;">

          <!-- 画像 -->
          <div style="flex: 0 0 25%;">
            <div class="index-photo">
              <%= image_tag parfait.parfait_image.present? ? parfait.parfait_image : 'noimage.png' %>
            </div>  
          </div>

          <div style="flex: 1; padding-left: 1rem;">
            <div class="d-flex">
              <h4>
                <%= link_to parfait.name, parfait_path(parfait) %>
              </h4>
              <% if user_signed_in? %>
                <% if current_user.own?(parfait) %>
                  <div class="ms-auto d-flex">
                    <%= link_to edit_parfait_path(parfait), id: "button-edit-#{parfait.id}", class: "me-2" do %>
                      <i class='bi bi-pencil-fill'></i> 編集
                    <% end %>
                    <%= link_to parfait_path(parfait), id: "button-delete-#{parfait.id}", data: { turbo_method: :delete, turbo_confirm: t('defaults.delete_confirm') } do %>
                      <i class="bi bi-trash-fill"></i> 削除
                    <% end %>
                  </div>
                <% end %>  
              <% end %>
            </div>

            <div>
              <%= link_to parfait.shop.name, shop_path(parfait.shop) %>
            </div>

            <div class="custom-line"></div>

            <div>価格帯：<%= parfait.price_i18n %></div>
            <% if parfait.is_limited? %> 
              <div>期間限定商品</div>
            <% else %>
              <div>レギュラー商品</div>
            <% end %> 
            <div>評価：</div>
            <div title="評価機能は後で実装予定です！お楽しみに！", class="star-size">☆☆☆☆☆</div>
            <% counts = @parfait_counts[parfait.id] %>
            <p>レビュー： <%= counts&.reviews_count || 0 %>件</p>
          </div>
        </div>

        <div class="custom-line"></div>
      <% end %>
    <% else %>
      <div class="mb-3 no-date">パフェの情報がありません</div>
    <% end %>
    <div class="p-2">
      <%= paginate @parfaits, theme: 'bootstrap-5' %>
    </div>
  </div>
</div>

app/views/parfaits/new.html.erb
<div class="form-wrapper">
    <div class="container parfait-page">
      <h2>商品登録</h2>
      <%= render 'form', parfait: @parfait %>
    </div>
</div>

app/views/parfaits/show.html.erb
<% breadcrumb :parfait_show, @parfait %>
<div class="show-wrapper">
  <div class="container show-page pt-3">  
    <div class="tabs">
      <ul class="nav nav-tabs">
        <li class="nav-item">
          <button class="nav-link active" data-bs-toggle="tab" data-bs-target="#section1" type="button">トップ</button>
        </li>
        <li class="nav-item">
          <button class="nav-link" data-bs-toggle="tab" data-bs-target="#section2" type="button">レビュー一覧</button>
        </li>
      </ul>
      
      <div class="tab-content">
        <div id="section1" class="tab-pane fade show active">
          <%= render 'parfaits/top_section_tab', parfait: @parfait %>
        </div>
        <div id="section2" class="tab-pane fade">
          <%= render 'parfaits/reviews_section_tab', reviews: @reviews, parfait: @parfait, bookmark_counts: @bookmark_counts %>
        </div>
      </div>
    </div>
  </div>
</div> 